{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/matei/Projects/Lyrics-Classification",
    "dependencies": [
      "numpy==1.16.2",
      "sacred==0.7.4",
      "scikit-learn==0.20.3",
      "tensorflow==1.13.1"
    ],
    "mainfile": "t.py",
    "name": "tfid_neural_network",
    "repositories": [],
    "sources": [
      [
        "preprocessing.py",
        "_sources/preprocessing_cc818be136265f2a352c369e9d26b626.py"
      ],
      [
        "t.py",
        "_sources/t_013193e9b2bd044de9be9fc67c73255a.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/matei/anaconda3/envs/machine_learning/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"t.py\", line 42, in main\n    model.fit(X_train, y)\n",
    "  File \"/home/matei/anaconda3/envs/machine_learning/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py\", line 776, in fit\n    shuffle=shuffle)\n",
    "  File \"/home/matei/anaconda3/envs/machine_learning/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py\", line 2382, in _standardize_user_data\n    exception_prefix='input')\n",
    "  File \"/home/matei/anaconda3/envs/machine_learning/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py\", line 362, in standardize_input_data\n    ' but got array with shape ' + str(data_shape))\n",
    "ValueError: Error when checking input: expected dense_input to have shape (100000,) but got array with shape (61803,)\n"
  ],
  "heartbeat": "2019-05-10T10:31:38.830687",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz",
    "gpus": {
      "driver_version": "418.56",
      "gpus": [
        {
          "model": "GeForce GTX 1060 with Max-Q Design",
          "persistence_mode": false,
          "total_memory": 6078
        }
      ]
    },
    "hostname": "matei",
    "os": [
      "Linux",
      "Linux-4.15.0-48-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.6.8"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-05-10T10:31:33.412145",
  "status": "FAILED",
  "stop_time": "2019-05-10T10:31:38.831730"
}